In [1]:
import torch

In [2]:
transformer_model = torch.nn.Transformer(nhead=1, num_encoder_layers=12, d_model=3)
src = torch.rand((100, 3, 3))
tgt = torch.rand((100, 3, 3))
out = transformer_model(src, tgt)

In [3]:
src[0]

tensor([[0.5353, 0.9513, 0.7292],
        [0.5780, 0.6787, 0.4052],
        [0.6485, 0.3102, 0.3232]])

In [4]:
tgt[0]

tensor([[0.7283, 0.8053, 0.6278],
        [0.8775, 0.9382, 0.4982],
        [0.0969, 0.3624, 0.0421]])

In [5]:
out[0]

tensor([[-1.3905,  0.4717,  0.9187],
        [-1.3997,  0.5250,  0.8747],
        [-1.3756,  0.4036,  0.9720]], grad_fn=<SelectBackward>)