In [1]:
import torch

In [2]:
transformer_model = torch.nn.Transformer(nhead=1, num_encoder_layers=12, d_model=3)
src = torch.rand((100, 3, 3, 3))
tgt = torch.rand((100, 3, 3, 3))
# out = transformer_model(src, tgt)

In [3]:
src[0]

tensor([[[0.3315, 0.5658, 0.3146],
         [0.1168, 0.2926, 0.2230],
         [0.6852, 0.0062, 0.8144]],

        [[0.4144, 0.6041, 0.1735],
         [0.2053, 0.3496, 0.0726],
         [0.4053, 0.6101, 0.8128]],

        [[0.6289, 0.4615, 0.8786],
         [0.7001, 0.1040, 0.1467],
         [0.7462, 0.5136, 0.6664]]])

In [4]:
x = torch.flatten(src[0], start_dim=1)
# x = torch.flatten(x, 1, 1)
x

tensor([[0.3315, 0.5658, 0.3146, 0.1168, 0.2926, 0.2230, 0.6852, 0.0062, 0.8144],
        [0.4144, 0.6041, 0.1735, 0.2053, 0.3496, 0.0726, 0.4053, 0.6101, 0.8128],
        [0.6289, 0.4615, 0.8786, 0.7001, 0.1040, 0.1467, 0.7462, 0.5136, 0.6664]])

In [5]:
out[0]

tensor([[-1.3905,  0.4717,  0.9187],
        [-1.3997,  0.5250,  0.8747],
        [-1.3756,  0.4036,  0.9720]], grad_fn=<SelectBackward>)